App/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired

class MyForm(FlaskForm):
  
    email = StringField('email',validators=[DataRequired()])
    pasword = StringField('password',validators=[DataRequired()])
    eth_address = StringField('eth_address',validators=[DataRequired()])

App/__init__.py
from flask import Flask
from config import Config 
import os, config
from views.home import home
import datetime
from datetime import *
# create application instance


app = Flask(__name__)
app.config.from_object(Config)
app.register_blueprint(home)


if __name__ =='__main__':
    app.run(host='0.0.0.0')

App/views/home.py
from flask import Blueprint, render_template,flash,redirect, url_for, session
import os 
from flask import jsonify, request
from database import db, users
import bcrypt  
from forms import MyForm


from pymongo import MongoClient
from config import Config 

client = MongoClient(Config.MONGO_DATABASE_URI)
db = client.SimlarityDB

users = db["Users"]
home = Blueprint('home',__name__,url_prefix='/')


def alreadyRegistered(email):
    if users.find({"email":email}).count()== 0:
        return False
    else :
        return True 

@home.route('/')
def index():
    return render_template('home/index.html')

@home.route('/about')
def about():
    return render_template('home/about.html')



@home.route('/register', methods = ['Get','POST'])
def register():
    if request.method == 'GET':
        return render_template('home/register.html')
    
    else:
        #postedData = request.get_json()
        email = request.form.get("email")
        username = email.split('@')[0]
        eth_address = request.form.get("eth_address")
        print(eth_address)
        password = request.form.get("password")
        print(password)
        hashed_pw = bcrypt.hashpw(password.encode('utf8'), bcrypt.gensalt())
        if alreadyRegistered(email) == True:
            retJson = {
                "status": 301,
                "msg": "User Already registered!"
            }
            return jsonify(retJson)
        hashed_pw = bcrypt.hashpw(password.encode('utf8'), bcrypt.gensalt())

        users.insert({
            "username": username,
            "email": email,
            "pasword": password,
            "eth_address": eth_address
        })
        return redirect(url_for('home.index'))

    


@home.route('/roadmap')
def map():
    return render_template('home/map.html')

App/templates/about/about.html
{% extends '../base.html' %}

{% block content %}
<div class = 'container'>
    <h2>Pure Blood NFT Yacht Club Value Proposition</h2>
      <div class="card" style="width: 18rem;">
           <div class="card-header">
            
            </div>
          <div class="embed-responsive embed-responsive-4by3">
            <iframe width="420" height="315" src="https://www.youtube.com/embed?v=rhirxE62rWs&ab_channel=TrentonGaddis" frameborder="0" allowfullscreen></iframe>

          </div>
          <div class="card-body">
            <p class="card-text">Why Join PURE BLOOD NFT?.</p>
          </div>
    </div>
    
    <div class="card" style="width: 18rem;">
  <img src="https://media-exp1.licdn.com/dms/image/C4E12AQFOQ-Nkfa9IOA/article-cover_image-shrink_600_2000/0/1538417966868?e=1651708800&v=beta&t=85hu0Kf7fxSMWq9Z0NDShZCh5lHocnTaeTetRkqp9P4"     class="card-img-top" alt="...">
    <div class="card-body">
      <p class="card-text">What is Self-Sovereign Identity and Why do we need it on the Blockchain?.</p>
    </div>
  </div>
 </div>

{% endblock %}

App/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
    <div class="row row-lg-4">
    <div class="col">

    
    <div class="container">
        {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

App/templates/home/about.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='about.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">

    <title>Pure Blood NFT Yacht Club</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-3">
                    <div class="card" style="width: 18rem;">
                        <div class="card-header">
                            Pure Blood NFT Yacht Club Value Proposition
                        </div>
                        <div class="embed-responsive embed-responsive-4by3">
                            <iframe width="420" height="315" src="{{url_for('static',filename='Pure Blood Yacht Club NFT Promo Video.mp4')}}" frameborder="0" allowfullscreen></iframe>
                
                        </div>
                        <div class="card-body">
                            <p class="card-text">Why Join PURE BLOOD NFT?.</p>
                        </div>
                    </div>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="card" style="width: 18rem;">
                    <img src="{{url_for('static',filename='sovereignIdentity.png')}}"     class="card-img-top" alt="...">
                      <div class="card-body">
                        <p class="card-text">What is Self-Sovereign Identity and Why do we need it on the Blockchain?.</p>
                      </div>
                    </div>
              </div>
         
        </div>
      </div>




    <div class="container">
        <div class="row">
          

    
         
        </div>
         
     </div>
      


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

App/templates/home/about2.html
{% extends 'base.html' %}

{% block content %}
<div class = 'container'>
    <h2>Pure Blood NFT Yacht Club Value Proposition</h2>
      <div class="card" style="width: 18rem;">
           <div class="card-header">
            
            </div>
          <div class="embed-responsive embed-responsive-4by3">
            <iframe width="420" height="315" src="{{url_for('static',filename='Pure Blood Yacht Club NFT Promo Video.mp4')}}" frameborder="0" allowfullscreen></iframe>

          </div>
          <div class="card-body">
            <p class="card-text">Why Join PURE BLOOD NFT?.</p>
          </div>
    </div>
    
    <div class="card" style="width: 18rem;">
  <img src="{{url_for('static',filename='sovereignIdentity.png')}}"     class="card-img-top" alt="...">
    <div class="card-body">
      <p class="card-text">What is Self-Sovereign Identity and Why do we need it on the Blockchain?.</p>
    </div>
  </div>
 </div>

{% endblock %}

App/templates/home/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">

    <title>Pure Blood NFT Yacht Club</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div id="banner2">

        <h1 >
            Become A Member of Pure Blood NFT Yacht Club and Restore your Individual Sovereignty
        </h1>
    
            <h2>Member Benefits include:</h2>
            <ul>
                <li>
                    Free Entry to the Pure Blood Yacht
                </li>
                <li>
                    Meet-Ups with like minded members 
                </li>
                <li>
                    Free educational resources "window.location.href='
                </li>
            </ul>
            

          <a href="{{url_for('home.register')}}"><input type=”button” class="btn btn-info" value=Register></a> 

    
    </div>

    <div id ="banner">
        
        
    </div>
        
 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

App/templates/home/index2.html
{% extends 'base.html' %}

{% block content %}
<div>
    <div id="overlay-1608" class="overlay sos-iframe-loaded" style="display: none;">
        
    </iframe class ="divi-sos-iframe" src="{{url_for('static',filename='pexels-mali-meader-42091.jpg')}}" scrolling="yes" width="1608">
        

    <h1 class="heading heading-xxl strong-800 d-none d-lg-block">
        <i class="fab fa-github"></i>
        Become A Member of Pure Blood NFT Yacht Club and Restore your Individual Sovereignty
    </h1>

        <h2>Member Benefits include:</h2>
        <ol>
            <li>
                Free Engry to the Pure Blood Yacht
            </li>
            <li>
                Meet-Ups with like minded members 
            </li>
            <li>
                Free educational resources 
            </li>
        </ol>

</div>

{% endblock %}

App/templates/home/map.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PBY NFT</title>
    <!----CSS link----->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='map.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://use.fontawesome.com/431fcca6e4.js"></script>
</head>



  <body>
    {% include 'navbar.html' %}
    <div class="banner">
      <div class="wrapper-flex">
        <div class="container">
          <h1 class="name">Q1 2021</h1>
          <ul class "description">
            <li class"list">CoinGecko listing</l>
          <li class"list">CoinMarketCap listing</l>
        <li class"list">Pure Blood Yacht Club meme competition</l>
          <li class"list">Onboard more Pure Bloods & Pure Blood Yacht Club influencers</li>
          
            <span id="dots">...</span><span id="more">
          
            
      </ul>
      <button class="btn" oneclick"myFunction"()>Read More</button>
        </div>
    
        <div class="container">
           <h1 class="name">Q2 021</h1>
          <ul class "description">
            <li class"list">Multi-sig the Pure Blood<br> Yacht Club Donation address: </li>  
  
            <li class"list">NFT Pure Blood Yacht Club Passports</li>
              
            <li class"list">Pure Blood Yacht Club merch</li>
            <li class"list"> Get Pure Blood Yacht Club hash tags trending on Twitter
            </li>
            
        </ul>
          <button class="btn" oneclick"myFunction"()>Read More</button>
        </div>
    
        <div class="container">
          <h1 class="name">Q3 2021</h1>
          <ul class "description">
            <li class"list">risk awareness campaigns (inc. flyers, banners + incentivised sharing)
  
              <li class"list"> listed on major exchange(s)</li>
              
              <li class"list"> Build Pure Blood Yacht Club Tinder and Twitter alternatives</li>
          
          </ul>
          <button class="btn" oneclick"myFunction"()>Read More</button>
        </div>





    </div>
    
  </body>
 
</html>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

App/templates/home/register.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='registration.css') }}">

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
    <div class="row row-lg-4">
    <div class="col">

    
    <div class="container">
        {% block content %} 
        <div class="form-body1">
            <div class="row">
                <div class="form-holder">
                    <div class="form-content">
                        <div class="form-items">
                            <h3>Register Today</h3>
                            <p>Fill in the data below.</p>
                            <form class="requires-validation" method = "POST" action="{{url_for('home.register')}}"novalidate>
        
                                <div class="col-md-12">
                                   <input class="form-control" type="text" name="email" placeholder="Email" value="{{request.form['email']}}"required>
                                   <div class="valid-feedback">Email field is valid!</div>
                                   <div class="invalid-feedback">Email field cannot be blank!</div>
                                </div>
        
                                <div class="col-md-12">
                                    <input class="form-control" type="email" name="eth_address" placeholder="Eth Address" value="{{request.form['eth_address']}}" required>
                                     <div class="valid-feedback">Eth Address field is valid!</div>
                                     <div class="invalid-feedback">Eth Address field cannot be blank!</div>
                                </div>
        
                               <div class="col-md-12">
                                   
        
        
                               <div class="col-md-12">
                                  <input class="form-control" type="password" name="password" placeholder="Password" value="{{request.form['password']}}" required>
                                   <div class="valid-feedback">Password field is valid!</div>
                                   <div class="invalid-feedback">Password field cannot be blank!</div>
                               </div> 
        
                            <div class="form-check">
                              <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                              <label class="form-check-label">I confirm that all data are correct</label>
                             <div class="invalid-feedback">Please confirm that the entered data are all correct!</div>
                            </div>
                      
        
                                <div class="form-button mt-3">
                                    <button id="submit" type="submit" class="btn btn-primary">Register</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        
        
        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

App/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('home.index')}}">PUREBLOOD NFT YACHT CLUB</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('home.index')}}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('home.about')}}">About</a>
          </li>
         
            <li class="nav-item">
            <a class="nav-link" href="{{url_for('home.map')}}">Roadmap</a>
          </li>
        </li>
         
        <li class="nav-item">
        <a class="nav-link" href="{{url_for('home.register')}}">Register</a>
      </li>
        </ul>
        
      </div>
    </div>
  </nav>